// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckExternalChange():Promise<string>;

export function CreateDir(arg1:string,arg2:string):Promise<string>;

export function CreateFile(arg1:string,arg2:string):Promise<string>;

export function DeletePath(arg1:string):Promise<void>;

export function ExportHTML(arg1:string,arg2:string):Promise<string>;

export function ExportPDF(arg1:string,arg2:string):Promise<string>;

export function OpenFile():Promise<main.OpenedFile>;

export function OpenFolder():Promise<main.FolderTree>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function RefreshFolder(arg1:string):Promise<main.FolderTree>;

export function RenamePath(arg1:string,arg2:string):Promise<string>;

export function ResolvePath(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveImageFile(arg1:string,arg2:string):Promise<string>;

export function SaveToPath(arg1:string,arg2:string):Promise<void>;

export function SaveToPathForce(arg1:string,arg2:string):Promise<void>;

export function SetCurrentFile(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;
