// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckExternalChange() {
  return window['go']['main']['App']['CheckExternalChange']();
}

export function ConfirmDelete(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDelete'](arg1, arg2);
}

export function ConfirmDiscard() {
  return window['go']['main']['App']['ConfirmDiscard']();
}

export function ConfirmOverwrite() {
  return window['go']['main']['App']['ConfirmOverwrite']();
}

export function ConfirmRestoreBackup() {
  return window['go']['main']['App']['ConfirmRestoreBackup']();
}

export function CreateDir(arg1, arg2) {
  return window['go']['main']['App']['CreateDir'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function ExportHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function RefreshFolder(arg1) {
  return window['go']['main']['App']['RefreshFolder'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function ResolvePath(arg1, arg2) {
  return window['go']['main']['App']['ResolvePath'](arg1, arg2);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveToPath(arg1, arg2) {
  return window['go']['main']['App']['SaveToPath'](arg1, arg2);
}

export function SetCurrentFile(arg1) {
  return window['go']['main']['App']['SetCurrentFile'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}
